<?php

declare(strict_types=1);

namespace App\Doctrine;

use DateTimeImmutable;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\DateTimeTzImmutableType;
use Doctrine\DBAL\Types\Exception\InvalidFormat;
use Doctrine\DBAL\Types\Exception\InvalidType;

/**
 * PostgreSQL timestamptz preserves microseconds when values are generated by now().
 *
 * Doctrine DBAL's default datetimetz_immutable parser only accepts the platform
 * format without fractional seconds, so DB-generated timestamps such as
 * "2026-07-21 16:42:10.123456+00" fail during hydration.
 */
final class PostgresDateTimeTzImmutableType extends DateTimeTzImmutableType
{
    public function convertToDatabaseValue(mixed $value, AbstractPlatform $platform): ?string
    {
        if ($value === null) {
            return null;
        }

        if ($value instanceof DateTimeImmutable) {
            return $value->format('Y-m-d H:i:s.uO');
        }

        throw InvalidType::new(
            $value,
            static::class,
            ['null', DateTimeImmutable::class],
        );
    }

    public function convertToPHPValue(mixed $value, AbstractPlatform $platform): ?DateTimeImmutable
    {
        if ($value === null || $value instanceof DateTimeImmutable) {
            return $value;
        }

        try {
            return parent::convertToPHPValue($value, $platform);
        } catch (InvalidFormat) {
            try {
                return new DateTimeImmutable($value);
            } catch (\Exception $exception) {
                throw InvalidFormat::new(
                    $value,
                    static::class,
                    $platform->getDateTimeTzFormatString(),
                    $exception,
                );
            }
        }
    }
}
